name: NuxArrows
version: 1.1.3
author: N4th4
main: net.n4th4.bukkit.nuxarrows.NuxArrows
  
permissions:
    nuxarrow.*:
        description: Give access to all NuxArrows nodes
        children:
            nuxarrow.infinite: true
    nuxarrow.infinite:
        description: Allow you to have infinite arrow
        default: op
